export const myProjects =[
    {
        id:"1",
        title: " Rockerz 450 boAt | DC edition",
        desc: "There is no better justice to your playlist & binging than Rockerz 470 boAt | DC edition. If low battery is your enemy, the 15HRS non-stop playback is here ",
        category: "headphone",
        img: "./img/download (2).jpg",
        price: 4199,
    },
    {
        id:"2",
        title: "Rockerz 400",
        desc: "Let's put an end to your worries about wires hanging and getting tangled with BoAt Rockerz 400 and connect with any Bluetooth device, connect and play.",
        category: ["headphone"],
        img: "./img/headphones-audio-listen.jpg",
        price: 1299,
    },
    {
        id:"3",
        title: "Rockerz 440",
        desc: "Let's put an end to your worries about wires hanging and getting tangled with BoAt Rockerz 400 and connect with any Bluetooth device, connect and play.",
        category: ["headphone"],
        img: "./img/images (5).jpg",
        price: 3598,
    },
    {
        id:"4",
        title: "Rockerz 450 Superman DC Edition - Wireless Bluetooth Headphone",
        desc: "There is no better justice to your playlist than Rockerz 450 boAt | DC edition. If low battery is your enemy, ",
        category: ["headphone"],
        img: "./img/11eaf1b9-79a1-4ad3-b8a6-db952d75bdd4.jpg",
        price: 2399,
    },
    {
        id:"5",
        title: " Rockerz 450 boAt | DC edition",
        desc: "There is no better justice to your playlist & binging than Rockerz 470 boAt | DC edition. If low battery is your enemy, the 15HRS non-stop playback is here ",
        category: ["headphone"],
        img: "./img/26e0a312-d398-4124-9ecb-4b3de254e41e.jpg",
        price: 1999,
    },
    {
        id:"6",
        title: "Trebel Rockerz 550 Wireless Bluetooth Headphones",
        desc: "Ladies, the time hath come to reach the wall of fame. Make your hustle shine like a diamond with TRebel Rockerz 550 — an audio partner that’s made to suit ",
        category: ["headphone"],
        img: "./img/c0b3069c-cbb4-4234-b85e-9573d8bbb8f6.jpg",
        price: 4599,
    },
    {
        id:"7",
        title: "boAt Rockerz 450 DC edition",
        desc: "There is no better justice to your playlist & binging than Rockerz 450 boAt | DC edition. If low battery is your enemy, the 15HRS non-stop playback is here ",
        category: ["headphone"],
        img: "./img/d016298b-eb65-4c54-8d7c-8adbe9490ffc.jpg",
        price: 2399,
    },
    {
        id:"8",
        title: "boAt Rockerz 518 Wireless Headphone",
        desc: "Now just stop worrying about Wires hanging from here and there. Pair with any Bluetooth device, connect and play. Dead Batteries can kill your vibe. ",
        category: ["headphone"],
        img: "./img/f9d6dce2-533d-4ca0-87fe-bc479dbdf2ba.jpg",
        price: 1699,
    },
    {
        id:"9",
        title: "Smartwatch with Fitness Trackers, 1.69 HD Display",
        desc: "When you can be at the apex of your health, why compromise? Meet Watch Vertex, our all-new smartwatch that’s built to improve your lifestyle and ",
        category: ["smartwatch"],
        img: "./img/images (1).jpg",
        price: 2566,
    },
    {
        id:"10",
        title: "boAt Iris | Round Dial Smart Watch with 1.39 AMOLED Display",
        desc: "Shoutout to all who see the glass half full. It is time to switch over to the bright side. Watch Iris will get you through the week with a 7-day battery backup.",
        category: ["smartwatch"],
        img: "./img/images (2).jpg",
        price: 4499,
    },
    {
        id:"11",
        title: "boAt Iris | Round Dial Smart Watch with 1.59 AMOLED Display, Multiple Watch Faces",
        desc: "Shoutout to all who see the glass half full. It is time to switch over to the bright side. Watch Iris will get you through the week with a 7-day battery backup. ",
        category: ["smartwatch"],
        img: "./img/images (3).jpg",
        price: 4299,
    },
    {
        id:"12",
        title: " boAt Wave Neo | 1.29 HD Display, Upto 7 Days Battery Life, IP68 Sweat",
        desc: "Introducing a #NeoWay to live smart and stylish – the all-new Watch Wave Neo. Check everything that you need in a smartwatch and then get some more. ",
        category: ["smartwatch"],
        img: "./img/images (4).jpg",
        price: 8499,
    },
    {
        id:"13",
        title: "boAt Wave Neo | 1.69 HD Display, Upto 7 Days Battery Life, IP68 Sweat",
        desc: "Introducing a #NeoWay to live smart and stylish – the all-new Watch Wave Neo. Check everything that you need in a smartwatch and then get some more. ",
        category: ["smartwatch"],
        img: "./img/download.jpg",
        price: 3599,
    },
    {
        id:"14",
        title: "boAt Wave Neo | 1.9 HD Display, Upto 7 Days Battery Life, IP68 Sweat",
        desc: "Introducing a #NeoWay to live smart and stylish – the all-new Watch Wave Neo. Check everything that you need in a smartwatch and then get some more. ",
        category: ["smartwatch"],
        img: "./img/images.jpg",
        price: 7199,
    },
    {
        id:"15",
        title: "boAt Vertex | Smartwatch with Fitness Trackers, 1.69 HD Display",
        desc: "When you can be at the apex of your health, why compromise? Meet Watch Vertex, our all-new smartwatch that’s built to improve your lifestyle",
        category: ["smartwatch"],
        img: "./img/download (1).jpg",
        price: 2299,
    },
    {
        id:"16",
        title: " Round Dial Smart Watch with 1.49 AMOLED ",
        desc: ". Watch Iris will get you through the week with a 7-day battery backup. ",
        category: ["smartwatch"],
        img: "./img/AdobeStock_97485309_Preview.jpeg",
        price: 3199,
    },{
        id:"17",
        title: "boAt Stone 800 - Portable Bluetooth Speaker",
        desc: "Wherever the party is tonight, make sure you carry the powerful 30000W R.M.S Sound of the PartyPal 800 along. It’s time to create memories with wireless ",
        category: ["speaker"],
        img: "./img/images (6).jpg",
        price: 9.599,
    },
    {
        id:"18",
        title: "boAt Party Pal 60 - Bluetooth Speaker",
        desc: "Immerse in the 20000W RMS Stereo Sound with the powerful Party Pal 60 bluetooth speaker. Set the vibes of the party just right with the RGB LEDs. Keep ",
        category: ["speaker"],
        img: "./img/images (7).jpg",
        price: 8.999,
    },
    {
        id:"19",
        title: "boAt Party Pal 50 - Bluetooth Speaker",
        desc: "Immerse in the 20W RMS Stereo Sound with the powerful Party Pal 50 bluetooth speaker. Set the vibes of the party just right with the RGB LEDs. Keep ",
        category: ["speaker"],
        img: "./img/images (8).jpg",
        price: 3799,
    },
    {
        id:"20",
        title: "Stone 382 - Wireless Portable Bluetooth Speaker",
        desc: "Be the life of every party as you carry the ultra-portable Stone 382 with you, wherever you go. Its 3W Stereo boAt Signature Sound will make you ",
        category: ["speaker"],
        img: "./img/download (3).jpg",
        price: 399,
    },
    {
        id:"21",
        title: "Stone 352 - Wireless Portable Bluetooth Speaker",
        desc: "Be the life of every party as you carry the ultra-portable Stone 352 with you, wherever you go. Its 10W Stereo boAt Signature Sound will make you ",
        category: ["speaker"],
        img: "./img/download (4).jpg",
        price: 1699,
    },
    {
        id:"22",
        title: "Stone 2000v2",
        desc: "Powerful and Precise. Stone 1000v2 is the premier wireless speaker that provides the best audio in the business. With its 14000W stereo sound,",
        category: ["speaker"],
        img: "./img/download (5).jpg",
        price: 6399,
    },
    {
        id:"23",
        title: "Stone 1500F | 14W boAt Signature Sound with Passive Bass Radiator",
        desc: "Add life to all your parties with the ultimate jukebox - Stone 1200F bluetooth speaker. It’s powered by ",
        category: ["speaker"],
        img: "./img/download (6).jpg",
        price: 3999,
    },
    {
        id:"24",
        title: "Stone 1000v2",
        desc: "Powerful and Precise. Stone 1000v2 is the premier wireless speaker that provides the best audio in the business. With its 14W stereo sound",
        category: ["speaker"],
        img: "./img/download (7).jpg",
        price: 2999,
    },
    {
        id:"25",
        title: "Airdopes 131 DC Edition with 13 mm Drivers",
        desc: "Sleek. Comfortable. Stylish. And a splash of amazing acoustic powers. Airdopes 131 true wireless earbuds are equipped with 13mm drivers that offer you ",
        category: ["earbuds"],
        img: "./img/download (10).jpg",
        price: 1399,
    },
    {
        id:"26",
        title: "TRebel Airdopes 141 ",
        desc: "Hello sassy and fierce ladies! We see you soaring high for your dreams, and we want to support them. Let TRebel Airdopes 141 be your biggest cheerleader",
        category: ["earbuds"],
        img: "./img/download (11).jpg",
        price: 1499,
    },
    {
        id:"27",
        title: "boAt Airdopes 141 Pro | 12mm Drivers, Upto 45 Hours ",
        desc: "Take a step up on your listening experience with boAt Airdopes 141 Pro. Start playing your tracks on our best wireless earbuds and don't stop with a total",
        category: ["earbuds"],
        img: "./img/download (12).jpg",
        price: 2.199,
    },
    {
        id:"28",
        title: "boAt Airdopes 171 Pro",
        desc: "Take a step up on your listening experience with boAt Airdopes 171 Pro. Start playing your tracks on our best wireless earbuds and don't stop with a total ",
        category: ["earbuds"],
        img: "./img/download (9).jpg",
        price: 3.699,
    },
    {
        id:"29",
        title: "boAt Airdopes 441 | Wireless Earbuds with 6mm Driver For Immersive Sound",
        desc: "Plug Into Nirvana with boAt Airdopes 441 TWS earbuds to enjoy your music in a truly wireless way. It has the IWP (Insta Wake N’ Pair) Technology, ",
        category: ["earbuds"],
        img: "./img/images (9).jpg",
        price: 2499,
    },
    {
        id:"30",
        title: "boAt Airdopes 450",
        desc: "Plug Into Nirvana with boAt Airdopes 450 TWS earbuds to enjoy your music in a truly wireless way. It has the IWP (Insta Wake N’ Pair) Technology, ",
        category: ["earbuds"],
        img: "./img/download (13).jpg",
        price: 4.299,
    },
    {
        id:"31",
        title: "boAt TRebel Airdopes 402 | In-Ear Earbuds With 10mm Driver, IPX4 Sweat",
        desc: "The time hath come for you, my ladies, to walk with elegance dripping with every step you take. Let the royal shine and distinguish yourself from the crowd ",
        category: ["earbuds"],
        img: "./img/images (10).jpg",
        price: 899,
    },
    {
        id:"32",
        title: "boAt TRebel Airdopes 350",
        desc: ". Let the royal shine and distinguish yourself from the crowd DC edition. If low battery is your enemy, the 15HRS non-stop playback is here ",
        category: ["earbuds"],
        img: "./img/download (8).jpg",
        price: 2999
    }
    
]
